CREATE PROC FI_SP_IncBeneficiario
    @CPF           VARCHAR (11) ,    
    @NOME          VARCHAR (50) ,
    @CPFCLIENTE    VARCHAR (11)
 
AS
BEGIN
	
    
    INSERT INTO BENEFICIARIOS (CPF, NOME, IDCLIENTE) 
	VALUES (@CPF, @NOME,(SELECT ID FROM CLIENTES WHERE CPF = @CPFCLIENTE))

	SELECT SCOPE_IDENTITY()
END